name: atl03landseamask
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - h5py
  - pandas
  - geopandas
  - matplotlib
  - shapely
  - pillow
  - python>=3.6
  - plotly
  - rasterio
  - scikit-learn
  - descartes
