name: atl03landseamask
channels:
  - defaults
dependencies:
  - jupyter
  - re
  - os
  - copy
  - h5py
  - pandas
  - geopandas
  - matplotlib
  - shapely
  - pillow
  - python>=3.6
  - bokeh
  - plotly
  - rasterio
  - scikit-learn
  - conda-forge::descartes
  - pip
